#logging:
#  level:
#    root: warn
#    com:
#      example: debug
#  pattern:
#    console: '%-5level %C.%M[%line] - %msg%n'

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/security?serverTimeZone=Asia/Shanghai"
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver